[project]
name = "agentic-ai-with-langgraph-and-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=0.3.26",
    "langgraph>=0.4.8",
    "langsmith>=0.4.1",
]
